basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: Swagger Example API
  version: "1.0"
paths:
  /sign-in:
    post:
      description: Метод для авторизации пользователя
      operationId: signIn
      responses: {}
      summary: Авторизация пользователя
  /sign-up:
    post:
      description: Метод для регистрации пользователя
      operationId: signUp
      responses: {}
      summary: Регистрация пользователя
swagger: "2.0"
